// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1OYbBqXh1EUVTyQtbl7JLHzxaXnDH4vw',
    appId: '1:393964697476:web:740117ffdc265149b04fd1',
    messagingSenderId: '393964697476',
    projectId: 'tp-flutter-cd82b',
    authDomain: 'tp-flutter-cd82b.firebaseapp.com',
    storageBucket: 'tp-flutter-cd82b.firebasestorage.app',
    measurementId: 'G-C608MGWMQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9qitb5JcGhd7fzuR18ysRIChQU_CBjY',
    appId: '1:393964697476:android:574ef06170fabd0eb04fd1',
    messagingSenderId: '393964697476',
    projectId: 'tp-flutter-cd82b',
    storageBucket: 'tp-flutter-cd82b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwEDe1iJJ4tqE5JJl6xf8Tg5YgGUiIQGA',
    appId: '1:393964697476:ios:e11cf88673f1f199b04fd1',
    messagingSenderId: '393964697476',
    projectId: 'tp-flutter-cd82b',
    storageBucket: 'tp-flutter-cd82b.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwEDe1iJJ4tqE5JJl6xf8Tg5YgGUiIQGA',
    appId: '1:393964697476:ios:e11cf88673f1f199b04fd1',
    messagingSenderId: '393964697476',
    projectId: 'tp-flutter-cd82b',
    storageBucket: 'tp-flutter-cd82b.firebasestorage.app',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1OYbBqXh1EUVTyQtbl7JLHzxaXnDH4vw',
    appId: '1:393964697476:web:d22a5e6bc4d29c25b04fd1',
    messagingSenderId: '393964697476',
    projectId: 'tp-flutter-cd82b',
    authDomain: 'tp-flutter-cd82b.firebaseapp.com',
    storageBucket: 'tp-flutter-cd82b.firebasestorage.app',
    measurementId: 'G-WVJT4XL8F3',
  );
}
